// Chat UI (core-only)

// Re-export everything from SDK
export {
  // Runtime
  AgentRuntime,
  // Provider config
  API_TYPES,
  type ApprovalRequest,
  // Skills
  addSkill,
  // Message utilities
  agentMessagesToChatMessages,
  applyProxyToModel,
  // Tools
  bashTool,
  // OAuth
  buildAuthorizationUrl,
  buildCustomModel,
  buildDefaultPlan,
  buildSkillsPromptSection,
  type ChatMessage,
  // Storage
  type ChatSession,
  configureNamespace,
  createSession,
  // Truncation
  DEFAULT_MAX_BYTES,
  DEFAULT_MAX_LINES,
  type Disposable,
  defineTool,
  // VFS
  deleteFile,
  deleteSession,
  deriveStats,
  type ExecutionUnit,
  // Lockdown
  ensureLockdown,
  exchangeOAuthCode,
  extractPartsFromAssistantMessage,
  type FetchProvider,
  type FetchResult,
  fetchWeb,
  fileExists,
  formatFingerprintCheckHook,
  formatFingerprintPreHook,
  formatFingerprintRecordHook,
  formatSize,
  generateId,
  generatePKCE,
  getBash,
  getFileType,
  getInstalledSkills,
  getLatestPlanRecord,
  getLatestTaskRecord,
  getNamespace,
  getOrCreateCurrentSession,
  getOrCreateDocumentId,
  getSession,
  getSessionMessageCount,
  getSharedCustomCommands,
  getVfs,
  type HandoffPacket,
  HookRegistry,
  type ImageSearchOptions,
  type ImageSearchProvider,
  type ImageSearchResult,
  listFetchProviders,
  listImageSearchProviders,
  listSearchProviders,
  listSessions,
  listUploads,
  loadOAuthCredentials,
  loadPdfDocument,
  loadSavedConfig,
  loadVfsFiles,
  // Web
  loadWebConfig,
  type MessagePart,
  OAUTH_PROVIDERS,
  type OAuthCredentials,
  type OAuthFlowState,
  PatternRegistry,
  PlanManager,
  type PlanMode,
  type PlanRecord,
  type PlanRevisionNote,
  type PlanStatus,
  type PlanStep,
  type ProviderConfig,
  parseSkillMeta,
  type ReasoningPattern,
  ReflectionEngine,
  type ReflectionEntry,
  type ReflectionLevel,
  type ReflectionResult,
  type RuntimeAdapter,
  type RuntimeMode,
  type RuntimeState,
  readBeforeWritePostHook,
  readBeforeWritePreHook,
  readFile,
  readFileBuffer,
  readTool,
  refreshOAuthToken,
  removeOAuthCredentials,
  removeSkill,
  renameSession,
  resetVfs,
  resizeImage,
  restoreVfs,
  type ScopeRiskEstimate,
  type SearchOptions,
  type SearchProvider,
  type SearchResult,
  type SessionStats,
  type SkillInput,
  type SkillMeta,
  type StorageNamespace,
  // Sandbox
  sandboxedEval,
  saveConfig,
  saveOAuthCredentials,
  saveSession,
  saveVfsFiles,
  saveWebConfig,
  searchImages,
  searchWeb,
  setCustomCommands,
  setSkillFiles,
  setStaticFiles,
  snapshotVfs,
  stripEnrichment,
  syncSkillsToVfs,
  type TaskClassification,
  TaskClassifier,
  type TaskRecord,
  type TaskRecordEntry,
  type TaskStatus,
  TaskTracker,
  THINKING_LEVELS,
  type ThinkingLevel,
  type ToolCallStatus,
  type ToolResult,
  type ToolTag,
  toBase64,
  toolError,
  toolSuccess,
  toolText,
  truncateHead,
  truncateTail,
  type UploadedFile,
  type VerificationContext,
  VerificationEngine,
  type VerificationIntent,
  type VerificationResult,
  type VerificationRunSummary,
  type VerificationStatus,
  type VerificationSuite,
  type WebConfig,
  type WebContext,
  writeFile,
} from "@office-agents/sdk";
export type {
  AppAdapter,
  ChatTab,
  ToolExtrasProps,
} from "./chat";
export { ChatInterface, FilesPanel, getChatContext } from "./chat";
export { default as ErrorBoundary } from "./chat/error-boundary.svelte";
